spring:
  application:
    name: '@project.name@'
  profiles:
    active: '@spring.profiles.active@'
  jta:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
  cache:
    jcache:
      config: classpath:cache/ehcache.xml
logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    fr.training.samples.spring.shop: INFO