spring:
  datasource:
    url: jdbc:mysql://158.101.164.60:3306/formationdb
    username: springUser
    password: ThePassword
#Monitoring endpoints   
management:
   endpoints:
      web:
         exposure:
            include: info, health, configprops, logfile, metrics, env, loggers

#logging:
  #level:
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
springdoc:
  show-actuator: true